# Generated by Django 2.2 on 2019-05-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksinsert',
            name='bquantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
