# Generated by Django 2.2 on 2019-05-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_lms', '0002_booksinsert_bquantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksShelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbshelf', models.CharField(max_length=400)),
                ('cbcreated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'booksshelf',
            },
        ),
        migrations.CreateModel(
            name='BooksType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbtype', models.CharField(max_length=400)),
                ('cbcreated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bookstype',
            },
        ),
    ]
