# Generated by Django 2.2 on 2019-05-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_lms', '0003_booksshelf_bookstype'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcolor', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'headercolor',
            },
        ),
    ]
