# Generated by Django 2.2 on 2019-05-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_lms', '0005_stuinsert'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuDept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdept', models.CharField(max_length=400)),
                ('cscreated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'studept',
            },
        ),
        migrations.CreateModel(
            name='StuSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csession', models.CharField(max_length=400)),
                ('cscreated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stusession',
            },
        ),
    ]
