# Generated by Django 2.2 on 2019-08-07 14:08

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_lms', '0008_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='ndetails',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
