# Generated by Django 2.2 on 2019-08-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_lms', '0009_auto_20190807_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='ntitle',
            field=models.CharField(default='SEClms', max_length=500),
        ),
    ]
