# Generated by Django 2.2 on 2019-08-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_lms', '0010_news_ntitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine', models.IntegerField()),
            ],
            options={
                'db_table': 'fine',
            },
        ),
    ]
